// This file is generated by Prismic local builder. Update with care!

export { default as ContactForm } from './ContactForm'
export { default as RichTextModule } from './RichTextModule'
export { default as TextImageRight } from './TextImageRight'
